# TODO: This file would need to be generated by cucim!
import importlib


backend_info = {
    "name": "my_backend",
    "types": ["numpy:matrix"],
    "symbol_mapping": {},
}


def implements(symbol, docs="cucim docs"):
    """Helper decorator.  Since/if we name our modules identically to the
    main module, we can just do a simple replace the module and be done.
    """
    orig_symbol = symbol.replace("cucim.skimage", "skimage")

    backend_info["symbol_mapping"][orig_symbol] = {
        "impl_symbol": symbol,
        "doc_blurp": docs,
    }


# This seems to be a way to see if a package should be installed.
spec = importlib.util.find_spec("cucim")

if spec is not None:
    # Cucim should be available (we assume this)
    implements("cucim.skimage.filters:median")
    implements("cucim.skimage.filters:gaussian")
